%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
function strainModel = getOptimalStrain(model,option,OE)
switch option
%%%%%%%%%%%%%%%%%%%%%% . Saccharomyces cerevisiae . %%%%%%%%%%%%%%%%%%%%%%%
    %Delft strain for Aromatic AA's
    case 1
        %Define the mutant strain to test, column1: genes 2 modify
        modifications = {'YDR035W';'YGR087C';'YDR380W';...
                         'YPR060C';'YDR127W';'YNL316C';'YBR166C';...
                         'YHR137W';'YGL148W';'YJL121C';'YOR095C';'YLR354C';...
                         'YPR074C'};
        %column 2: 0 for deletions, 1 for overexpressions
        modifications = horzcat(modifications,{0;0;0;...
                                               1;1;1;1;...
                                               1;1;1;1;1;...
                                               1});
        %overexpression factors (assumed linear with respect to the OE for
        %promoters
        modifications = horzcat(modifications,{0;0;0;...
                                              OE;OE;OE;OE;...
                                              100;OE;25;10;2;...
                                              3});
        %get mutant strain
    %GUF1 strain for acetyl-CoA
    case 2
        modifications = {'YMR303C';'YMR083W';'YGL256W';'YBR145W';'YMR318C';'YDL168W';'YMR020W'};
        modifications = horzcat(modifications,{0;0;0;0;2;2;1});
        modifications = horzcat(modifications,{0;0;0;0;1.44*OE;15.7*OE;OE});
    %GUF2 strain for acetyl-CoA
    case 3
        modifications = {'YMR303C';'YMR083W';'YGL256W';'YBR145W';'YMR318C';'YDL168W';'YNR016C';'YDL022W'};
        modifications = horzcat(modifications,{0;0;0;0;2;2;1;2});
        modifications = horzcat(modifications,{0;0;0;0;1.44*OE;15.7*OE;OE;16.68});
%%%%%%%%%%%%%%%%%%%%%%%%%   Yarrowia lipolytica   %%%%%%%%%%%%%%%%%%%%%%%%%
    %INRA strain for aromatic aminoacids
    case 4
        %YALI0B20020g deletion removed from the mutant list because it
        %resulted to be an essential gene
        modifications = {'YALI0C06952g';'YALI0E17479g';'YALI0F12639g';'YALI0D17930g';...
                         'YALI0D06930g';'YALI0E06479g';'YALI0F00484g'};
        modifications = horzcat(modifications,{1;1;1;1;...
                                               0;1;1});
        modifications = horzcat(modifications,{OE;OE;OE;OE;...
                                                0;OE;OE});
    %INRa strain for Acetyl-CoA
    case 5
        modifications = {'YALI0C11407g';'YALI0F05962g'};
        modifications = horzcat(modifications,{1;1});
        modifications = horzcat(modifications,{OE;OE});
%%%%%%%%%%%%%%%%%%%%%%%%   Kluyveromyces marxianus   %%%%%%%%%%%%%%%%%%%%%%%
    %INRa strain for Aromatic AA's production
    case 6
        modifications = {'KLMA_40107';'KLMA_20414';'KLMA_80332';'KLMA_40161';...
                         'KLMA_70162';'KLMA_60423';'KLMA_80099';'KLMA_60024';...
                         'KLMA_80221';'KLMA_30634';'KLMA_80302';'KLMA_10462';...
                         'KLMA_60075';'KLMA_20597';'KLMA_20259';'KLMA_50151';...
                         'KLMA_50631'};
        modifications = horzcat(modifications,{0;1;1;1;...
                                               1;1;1;1;...
                                               1;1;1;1;...
                                               0;0;0;0;...
                                               0});
        modifications = horzcat(modifications,{0;OE;OE;OE;...
                                               OE;OE;OE;OE;...
                                               OE;OE;OE;OE;...
                                               0;0;0;0;0});
        %No proposal for Acetyl-CoA production
    case 7
        modifications = {''};
        modifications = horzcat(modifications,{5});
        modifications = horzcat(modifications,{10});
        
end
strainModel   = getMutant(model,modifications,true);
end